syumai/dinatra

README.md

I tried to run the script on README.md and I got an error below.
```
$ deno dinatra_sample.ts
Compiling /Users/TSUBASA/workspace/hoges/deno_hoges/dinatra_sample.ts
Downloading https://syumai.github.io/dinatra/dinatra.ts
Downloading https://deno.land/x/net/http.ts
Downloading https://syumai.github.io/dinatra/response
Downloading https://syumai.github.io/dinatra/response.ts
Downloading https://syumai.github.io/dinatra/errors
Downloading https://syumai.github.io/dinatra/errors.ts
Downloading https://deno.land/x/net/bufio.ts
Downloading https://deno.land/x/net/textproto.ts
Downloading https://deno.land/x/net/http_status
Downloading https://deno.land/x/net/http_status.ts
Downloading https://deno.land/x/net/util
Downloading https://deno.land/x/net/util.ts …
```

chore modify README.md

---

README.md
constants.ts
dinatra.ts

* Add option to set default port for web app.
```console
deno index.ts -p 8000 # or --port 8000
```

Add default port option

---

README.md
dinatra.ts
example/form/form.html
example/form/index.ts
example/index.ts

* Add support to read params from request body.
- application/x-www-form-urlencoded
- application/json

Add support of POST with simple form

---

.gitignore
example/form/form.html
example/form/index.ejs
example/form/index.ts

* Use ejs with [dpl](https://github.com/syumai/dpl) as example.

Use ejs for template of example app

---

constants.ts
mod.ts

Hi @syumai , refer to this issue #13 i've already fix on this commit. Thank you

Fix dependencies error

---

static_test.ts

Fixed dependencies of static test

---

dinatra.ts
mod.ts
static_test.ts

* Fix http module path.
* Fix testing to use runTests().
* https://github.com/denoland/deno_std/pull/170
* https://github.com/denoland/deno_std/pull/129

Fixed module path and test

---

response.ts

* Same as title.
* Changed to use this: https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards

Refactor: Changed to use User-defined Type Guards

---

.travis.yml
README.md
static_test.ts

* Added Travis CI config.
* Reverted to use pretty_assert.
* Changed static_test's async function scope.

Improve testing

---

constants.ts
mod.ts
static_test.ts

* Revert #20 because https://github.com/denoland/registry/pull/50 merged.

Remove std from import path

---

README.md
constants.ts
mod.ts
response.ts
static_test.ts

* Update to latest http module.
* Make app cancelable.
* Because the API of http has been changed.
- https://github.com/denoland/deno_std/pull/188

Update http module

---

README.md
constants.ts
example/form/index.ts
example/template/index.ts
mod.ts
response.ts

Updated to deno 0.3.0

---

mod.ts

* Fixed broken GET
* POST and other methods are still broken
* This resolves: #26

Fix get request

---

README.md
example/static_disabled/index.ts
mod.ts
static_test.ts

* Previous dinatra's path resolving order is below.
1. find static file
2. if file was not found, then find handler
* This PR reverses the order.
* This resolves #28 .

Reverse path resolving order

---

Makefile
serve_test.ts
static_test.ts

* Same as title.
* This resolves #11 .

Add test for normal serve

---

serve_test.ts

Fix async handler test

---

constants.ts
mod.ts
response.ts
serve_test.ts
static_test.ts

* Move from `deno.land/x/std` to `deno.land/std`
* Fix `assertEqual` to `assertEquals`

Updated module paths and fix test

---

mod.ts
std/http/readers.ts
std/http/server.ts

* Copied implementation of http server from deno_std@v0.2.11
* Fixed build errors

Fix build error

---

README.md
example/form/index.ejs
example/form/index.ts
mod.ts

* Supported multiple params of form data.

Fix form data parsing

---

mod.ts

This resolves https://github.com/syumai/denoboard/issues/1 .

Fixed form params decoding bug

---

mod.ts
response.ts

At https://github.com/denoland/deno_std/pull/449, some files of strings package are renamed.

Fix build errors

---

dem.json
vendor/https/deno.land/std/flags/mod.ts
vendor/https/deno.land/std/http/server.ts
vendor/https/deno.land/std/strings/mod.ts
vendor/https/deno.land/std/testing/asserts.ts
vendor/https/deno.land/std/testing/mod.ts

* Update std
```
dem update https://deno.land/std@v0.20.0
```

Updated to std@v0.20.0

---

dem.json
vendor/https/deno.land/std/flags/mod.ts
vendor/https/deno.land/std/http/server.ts
vendor/https/deno.land/std/strings/mod.ts
vendor/https/deno.land/std/testing/asserts.ts
vendor/https/deno.land/std/testing/mod.ts

```
dem update https://deno.land/std@v0.21.0
```

Update std to v0.21.0

---

README.md
example/index.ts
mod.ts
serve_test.ts

Basic support for **required** path parameters

Added support for path parameters

---

response.ts
serve_test.ts

If you run example and open http://localhost:8080/hello/wat dinatra will fail with
```
error: Uncaught Error: bad status code
► https://deno.land/std@v0.23.0/http/server.ts:67:11
67     throw Error("bad status code");
^
at writeResponse (https://deno.land/std@v0.23.0/http/server.ts:67:11)
at respond (https://deno.land/std@v0.23.0/http/server.ts:197:11)
at serve (mod.ts:215:17)
```
This PR fixes issue.

Fix params

---

README.md
dem.json
vendor/https/deno.land/std/flags/mod.ts
vendor/https/deno.land/std/http/server.ts
vendor/https/deno.land/std/strings/mod.ts
vendor/https/deno.land/std/testing/asserts.ts

Release 0.8.4

---

.github/workflows/test.yml

Update action config

---

dem.json
response.ts
vendor/https/deno.land/std/encoding/utf8.ts
vendor/https/deno.land/std/flags/mod.ts
vendor/https/deno.land/std/http/server.ts
vendor/https/deno.land/std/strings/mod.ts
vendor/https/deno.land/std/testing/asserts.ts

```sh
$ dem update https://deno.land/std@v0.40.0
$ dem prune
$ dem ensure
```

Updated std to v0.40.0

---

README.md

Release 0.10.1

---

Makefile
README.md
dem.json
helpers_test.ts
io.ts
mod.ts
response.ts
serve_test.ts
static_test.ts
vendor/https/deno.land/std/encoding/utf8.ts
vendor/https/deno.land/std/flags/mod.ts
vendor/https/deno.land/std/http/server.ts
vendor/https/deno.land/std/testing/asserts.ts

Release 0.12.0

---

README.md
dem.json
vendor/https/deno.land/std/encoding/utf8.ts
vendor/https/deno.land/std/flags/mod.ts
vendor/https/deno.land/std/http/server.ts
vendor/https/deno.land/std/testing/asserts.ts

Release 0.12.1

---

README.md
mod.ts

* Fix build error with `export type {} ...`

Release 0.14.0
